// packages/react-widget/src/components/FeedbackWidget.tsx
'use client'

import React, { useState } from 'react'

interface FeedbackWidgetStyles {
  button?: React.CSSProperties
  formContainer?: React.CSSProperties
  input?: React.CSSProperties
  textarea?: React.CSSProperties
  widgetContainer?: React.CSSProperties
  closeButton?: React.CSSProperties
}

interface FeedbackWidgetProps {
  /**
   * The URL of the feedback API endpoint.
   */
  feedbackApiUrl: string
  /**
   * Optional user data to associate with the feedback.
   */
  user?: {
    id: number | string
  }
  /**
   * Optional default value for the title.
   */
  defaultTitle?: string
  /**
   * Optional default value for the feedback.
   */
  defaultFeedback?: string
  /**
   * Optional default value for the breadcrumbs.
   */
  defaultBreadcrumbs?: string
  /**
   * Optional custom styles for the widget components.
   */
  customStyles?: FeedbackWidgetStyles
}

export const FeedbackWidget: React.FC<FeedbackWidgetProps> = ({
  feedbackApiUrl,
  user,
  defaultTitle = '',
  defaultFeedback = '',
  defaultBreadcrumbs = '',
  customStyles,
}) => {
  const [isOpen, setIsOpen] = useState(false)
  const [title, setTitle] = useState(defaultTitle)
  const [feedback, setFeedback] = useState(defaultFeedback)
  const [breadcrumbs, setBreadcrumbs] = useState(defaultBreadcrumbs)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<null | string>(null)
  const [success, setSuccess] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)
    setError(null)
    setSuccess(false)

    try {
      const response = await fetch(feedbackApiUrl, {
        body: JSON.stringify({
          breadcrumbs: breadcrumbs || 'Submitted via public widget',
          feedback,
          title,
          user: user?.id,
        }),
        headers: {
          'Content-Type': 'application/json',
        },
        method: 'POST',
      })

      const res = await response.json()

      if (!response.ok) {
        throw new Error(res.errors?.[0]?.message || 'Failed to submit feedback.')
      }

      setSuccess(true)
      setTitle('')
      setFeedback('')
      setBreadcrumbs('')
      setTimeout(() => {
        setIsOpen(false)
        setSuccess(false)
      }, 2000)
    } catch (err: any) {
      setError(err.message)
    } finally {
      setIsSubmitting(false)
    }
  }

  // Basic styling for the widget. Users can override this with their own styles.
  const defaultStyles = {
    button: {
      backgroundColor: '#007bff',
      border: 'none',
      borderRadius: '5px',
      color: 'white',
      cursor: 'pointer',
      padding: '10px 20px',
    },
    formContainer: {
      backgroundColor: 'white',
      border: '1px solid #ccc',
      borderRadius: '5px',
      boxShadow: '0 0 10px rgba(0,0,0,0.1)',
      padding: '20px',
      width: '300px',
    },
    input: {
      boxSizing: 'border-box',
      margin: '5px 0 10px 0',
      padding: '8px',
      width: '100%',
    },
    textarea: {
      boxSizing: 'border-box',
      margin: '5px 0 10px 0',
      minHeight: '100px',
      padding: '8px',
      width: '100%',
    },
    widgetContainer: {
      bottom: '20px',
      position: 'fixed',
      right: '20px',
      zIndex: 1000,
    },
    closeButton: {
      backgroundColor: '#6c757d',
      marginLeft: '10px',
    },
  } as const

  const styles = {
    button: { ...defaultStyles.button, ...customStyles?.button },
    formContainer: { ...defaultStyles.formContainer, ...customStyles?.formContainer },
    input: { ...defaultStyles.input, ...customStyles?.input },
    textarea: { ...defaultStyles.textarea, ...customStyles?.textarea },
    widgetContainer: { ...defaultStyles.widgetContainer, ...customStyles?.widgetContainer },
    closeButton: { ...defaultStyles.closeButton, ...customStyles?.closeButton },
  }

  return (
    <div style={styles.widgetContainer}>
      {isOpen ? (
        <div style={styles.formContainer}>
          <form onSubmit={handleSubmit}>
            <h3>Submit Feedback</h3>
            <input
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Title"
              required
              style={styles.input}
              type="text"
              value={title}
            />
            <textarea
              onChange={(e) => setFeedback(e.target.value)}
              placeholder="Describe your issue or idea..."
              required
              style={styles.textarea}
              value={feedback}
            />
            <input
              onChange={(e) => setBreadcrumbs(e.target.value)}
              placeholder="Breadcrumbs (optional)"
              style={styles.input}
              type="text"
              value={breadcrumbs}
            />
            <button disabled={isSubmitting} style={styles.button} type="submit">
              {isSubmitting ? 'Submitting...' : 'Submit'}
            </button>
            <button
              onClick={() => setIsOpen(false)}
              style={{ ...styles.button, ...styles.closeButton }}
              type="button"
            >
              Close
            </button>
            {error && <p style={{ color: 'red' }}>{error}</p>}
            {success && <p style={{ color: 'green' }}>Feedback submitted successfully!</p>}
          </form>
        </div>
      ) : (
        <button onClick={() => setIsOpen(true)} style={styles.button}>
          Feedback
        </button>
      )}
    </div>
  )
}

// packages/angular-widget/src/lib/feedback-widget.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { catchError, throwError, Observable } from 'rxjs';

export interface FeedbackSubmission {
  title: string;
  feedback: string;
  breadcrumbs?: string;
  userId?: string | number;
}

export interface FeedbackWidgetStyles {
  button?: Partial<CSSStyleDeclaration>;
  formContainer?: Partial<CSSStyleDeclaration>;
  input?: Partial<CSSStyleDeclaration>;
  textarea?: Partial<CSSStyleDeclaration>;
  widgetContainer?: Partial<CSSStyleDeclaration>;
  closeButton?: Partial<CSSStyleDeclaration>;
}

/**
 * Custom submission handler function type.
 * Receives the feedback payload and should return an Observable that completes on success.
 */
export type FeedbackSubmissionHandler = (
  payload: FeedbackSubmission,
) => Observable<any>;

@Component({
  selector: 'ff-feedback-widget',
  templateUrl: './feedback-widget.component.html',
  styleUrls: ['./feedback-widget.component.scss'],
  standalone: true,
  imports: [CommonModule, FormsModule],
})
export class FeedbackWidgetComponent implements OnInit {
  /**
   * API URL for feedback submission. Required if submitHandler is not provided.
   */
  @Input() feedbackApiUrl?: string;

  /**
   * Custom submission handler. If provided, this will be used instead of the default HTTP POST.
   * Should return an Observable that completes on success or errors on failure.
   *
   * Example:
   * ```typescript
   * customSubmitHandler = (payload: FeedbackSubmission) => {
   *   return this.myCustomHttpService.submitFeedback(payload);
   * }
   * ```
   */
  @Input() submitHandler?: FeedbackSubmissionHandler;

  @Input() userId?: string | number;
  @Input() defaultTitle?: string = '';
  @Input() defaultFeedback?: string = '';
  @Input() defaultBreadcrumbs?: string = '';
  @Input() customStyles?: FeedbackWidgetStyles;

  isOpen = false;
  title = '';
  feedback = '';
  breadcrumbs = '';
  isSubmitting = false;
  error: string | null = null;
  success = false;

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.title = this.defaultTitle || '';
    this.feedback = this.defaultFeedback || '';
    this.breadcrumbs = this.defaultBreadcrumbs || '';
  }

  toggleWidget(): void {
    this.isOpen = !this.isOpen;
    if (!this.isOpen) {
      this.resetForm();
    }
  }

  submitFeedback(): void {
    if (!this.title || !this.feedback) {
      return;
    }

    // Validate that either submitHandler or feedbackApiUrl is provided
    if (!this.submitHandler && !this.feedbackApiUrl) {
      this.error = 'Configuration error: Either submitHandler or feedbackApiUrl must be provided';
      return;
    }

    this.isSubmitting = true;
    this.error = null;
    this.success = false;

    const payload: FeedbackSubmission = {
      title: this.title,
      feedback: this.feedback,
      breadcrumbs: this.breadcrumbs || 'Submitted via Angular widget',
      userId: this.userId,
    };

    // Use custom handler if provided, otherwise use default HTTP POST
    let submission$: Observable<any>;

    try {
      submission$ = this.submitHandler
        ? this.submitHandler(payload)
        : this.http.post(this.feedbackApiUrl!, payload);
    } catch (error) {
      this.error = 'Failed to submit feedback: ' + (error instanceof Error ? error.message : 'Unknown error');
      this.isSubmitting = false;
      return;
    }

    submission$
      .pipe(
        catchError((error: HttpErrorResponse) => {
          this.error = error.error?.message || 'Failed to submit feedback';
          this.isSubmitting = false;
          return throwError(() => error);
        }),
      )
      .subscribe({
        next: (response) => {
          this.success = true;
          this.isSubmitting = false;
          this.resetForm();
          setTimeout(() => {
            this.isOpen = false;
            this.success = false;
          }, 2000);
        },
        error: (err) => {
          this.isSubmitting = false;
        },
      });
  }

  private resetForm(): void {
    this.title = '';
    this.feedback = '';
    this.breadcrumbs = '';
    this.error = null;
  }
}

<div class="feedback-widget-container" [ngStyle]="customStyles?.widgetContainer">
  <div *ngIf="isOpen" class="feedback-form-container" [ngStyle]="customStyles?.formContainer">
    <form (ngSubmit)="submitFeedback()">
      <h3>Submit Feedback</h3>

      <input
        type="text"
        [(ngModel)]="title"
        name="title"
        placeholder="Title"
        required
        [ngStyle]="customStyles?.input"
        class="feedback-input"
      />

      <textarea
        [(ngModel)]="feedback"
        name="feedback"
        placeholder="Describe your issue or idea..."
        required
        [ngStyle]="customStyles?.textarea"
        class="feedback-textarea"
      ></textarea>

      <input
        type="text"
        [(ngModel)]="breadcrumbs"
        name="breadcrumbs"
        placeholder="Breadcrumbs (optional)"
        [ngStyle]="customStyles?.input"
        class="feedback-input"
      />

      <div class="button-group">
        <button
          type="submit"
          [disabled]="isSubmitting"
          [ngStyle]="customStyles?.button"
          class="feedback-button"
        >
          {{ isSubmitting ? 'Submitting...' : 'Submit' }}
        </button>

        <button
          type="button"
          (click)="toggleWidget()"
          [ngStyle]="customStyles?.closeButton"
          class="feedback-button close-button"
        >
          Close
        </button>
      </div>

      <p *ngIf="error" class="error-message">{{ error }}</p>
      <p *ngIf="success" class="success-message">Feedback submitted successfully!</p>
    </form>
  </div>

  <button
    *ngIf="!isOpen"
    (click)="toggleWidget()"
    [ngStyle]="customStyles?.button"
    class="feedback-button toggle-button"
  >
    Feedback
  </button>
</div>
